[package]
name = "ootr_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2.8"
faithe = "0.7.0"
fltk = "^1.3"
fltk-flex = "0.2.1"
fltk-grid = "0.1"
glob = "0.3.0"